### ISSUE TITLE
如果utools是开源的就好了

### ISSUE THREAD

**Issue by SOVLOOKUP** [adams549659584/utools-app#1]
插件系统最大的优势就是拥有开源生态，但是官方却十分保守

如果utools开源，有一个去中心化的开源社区，那么一切都会好很多

你探索utools代码的目的是什么？我们能聊一聊吗？

**Comment by adams549659584** [comment]
之前发布了个插件，后来遇到个问题，在官方论坛求助（ https://yuanliao.info/d/2255-id ）也没人回应，只能自己魔改下

**Comment by SOVLOOKUP** [comment]
开源的版本来了，兼容utools插件生态，我打算加入开发

https://github.com/clouDr-f2e/rubick
